{
 "title": "OS Details",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "osnodes",
    "label": "Node",
    "query": "query_result( up{ exp_type = 'node' } )"
   }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"[[osnodes]]\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"[[osnodes]]\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"[[osnodes]]\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"user\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"iowait\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"idle\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"user\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"iowait\", job=\"[[osnodes]]\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"[[osnodes]]\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"[[osnodes]]\"} - node_memory_MemAvailable_bytes{job=\"[[osnodes]]\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"[[osnodes]]\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"[[osnodes]]\"}  ",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"[[osnodes]]\"} - node_memory_SwapFree_bytes{job=\"[[osnodes]]\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=\"[[osnodes]]\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-(100*(node_filesystem_free_bytes{job=\"[[osnodes]]\", fstype!~\".*tmpfs.*|.*root.*|.*pipe.*\"} / node_filesystem_size_bytes{job=\"[[osnodes]]\", fstype!~\".*tmpfs.*|.*root.*|.*pipe.*\"}))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100-(100*(node_filesystem_free{job=\"[[osnodes]]\", fstype!~\".*tmpfs.*|.*root.*|.*pipe.*\"} / node_filesystem_size{job=\"[[osnodes]]\", fstype!~\".*tmpfs.*|.*root.*|.*pipe.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}