{
 "title": "PGBackrest",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pgnodes",
    "label": "PGCluster",
    "query": "query_result( up{ exp_type = 'pg' } )"
   },
   {
    "name": "backrest_stanza",
    "label": "Stanza",
    "query": "query_result( ccp_backrest_last_info_backup_runtime_seconds{job=\"[[pgnodes]]\"} )"
   }
  ]
 },
 "panels": [
  {
   "title": "Time Since Last Completed Backup (Any)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_incr_backup_time_since_completion_seconds{job=\"[[pgnodes]]\",stanza=\"[[backrest_stanza]]\"}",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Backup Runtime (Any)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_info_backup_runtime_seconds{job=\"[[pgnodes]]\",stanza=\"[[backrest_stanza]]\"}",
     "legendFormat": "{{backup_type}}"
    }
   ]
  },
  {
   "title": "Backup Size (Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_info_repo_total_size_bytes{job=\"[[pgnodes]]\",stanza=\"[[backrest_stanza]]\"}",
     "legendFormat": "{{backup_type}}"
    }
   ]
  },
  {
   "title": "Backup Size (Actual)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_info_repo_backup_size_bytes{job=\"[[pgnodes]]\",stanza=\"[[backrest_stanza]]\"}",
     "legendFormat": "{{backup_type}}"
    }
   ]
  },
  {
   "title": "Time Since Last Completed Backup (Full)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_full_backup_time_since_completion_seconds{job=\"[[pgnodes]]\",stanza=\"[[backrest_stanza]]\"}",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Time Since Last Completed Backup (Full,Diff)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_diff_backup_time_since_completion_seconds{job=\"[[pgnodes]]\",stanza=\"[[backrest_stanza]]\"}",
     "legendFormat": "{{stanza}}"
    }
   ]
  }
 ]
}