---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-enable-external-services
patch: |-
  - op: add
    path: /spec/publishBinaryService
    value: true
  - op: add
    path: /spec/serviceTemplate
    value:
      spec:
        type: LoadBalancer
        loadBalancerSourceRanges: {{ LOADBALANCER_SOURCE_RANGES }}
{% if PROVIDER == "azure" and V4_CFG_ENABLE_IPV6 %}
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"
{% endif %}
{% if PROVIDER == "aws" %}
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
{% if V4_CFG_ENABLE_IPV6 %}
          service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "dualstack"
{% endif %}
{% endif %}
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  # This applies to the default CAS server:
  labelSelector: "sas.com/cas-server-default"
  version: v1alpha1
