# Copyright © 2020-2025, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Transformer for PostgreSQL StatefulSet in single-zone clusters with relaxed constraints
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: postgres-single-zone-distribution
patch: |-
  - op: add
    path: /spec/template/spec/topologySpreadConstraints
    value:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            postgres-operator.crunchydata.com/cluster: shared-postgres
  - op: add
    path: /spec/template/spec/affinity
    value:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - stateful
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: shared-postgres
              topologyKey: kubernetes.io/hostname
target:
  kind: StatefulSet
  name: ".*postgres.*"
  version: v1