# Copyright © 2020-2025, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Transformer to set topology spread constraints for stateless services (Deployments)
# Targets ALL Deployments - no selector (will apply to all including non-SAS)
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: stateless-zone-distribution
patch: |-
  - op: replace
    path: /spec/template/spec/topologySpreadConstraints
    value:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            sas.com/deployment: sas-viya
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            sas.com/deployment: sas-viya
target:
  kind: Deployment
  version: v1
  group: apps
