{
 "title": "SAS Launched Jobs - User Activity",
 "tags": [ "sas-viya" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_service_info{service=\"sas-launcher\"},namespace)"
   },
   {
    "name": "jobType",
    "label": "Job Type",
    "query": "sas-batch-job,compute-server,sas-launcher-job"
   },
   {
    "name": "user",
    "label": "User",
    "query": "label_values({namespace=~\"$namespace\"},label_launcher_sas_com_username)"
   },
   {
    "name": "pod",
    "label": "Job",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\", label_launcher_sas_com_job_type=~\"$jobType\",label_launcher_sas_com_username=~\"$user\",label_job_name=~\"sas-launcher-.+-.+-.+-.+-.+\"},pod)"
   },
   { "name": "top", "label": "Top", "query": "5,10,20,50" }
  ]
 },
 "panels": [
  { "title": "Current Active Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(:sas_launcher_pod_cpu_core_usage:{pod=~\"$pod\"}) or vector(0)",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(:sas_launcher_pod_mem_usage_bytes:{pod=~\"$pod\"}) or vector(0)",
     "legendFormat": "Total Memory Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", phase=~\"Pending\"}) or vector(0)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$pod\", phase=~\"Running\"}) or vector(0)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(:sas_launcher_pod_net_transmit_bytes_total:{pod=~\"$pod\"}[1m])) + sum(rate(:sas_launcher_pod_net_receive_bytes_total:{pod=~\"$pod\"}[1m])) or vector(0)",
     "legendFormat": "Network I/O"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(:sas_launcher_pod_fs_read_bytes_total:{pod=~\"$pod\"}[1m])) + sum(rate(:sas_launcher_pod_fs_write_bytes_total:{pod=~\"$pod\"}[1m])) or vector(0)",
     "legendFormat": "File I/O"
    }
   ]
  },
  { "title": "Top Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Workload Distribution by User",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "job(s)" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk($top,count(:sas_launcher_pod_status:{pod=~\"$pod\",phase=~\"Pending|Running\"}) by (label_launcher_sas_com_username)))",
     "legendFormat": "{{label_launcher_sas_com_username}}"
    }
   ]
  },
  {
   "title": "CPU Usage by User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "topk($top,sum(:sas_launcher_pod_cpu_core_usage:{pod=~\"$pod\"}) by (label_launcher_sas_com_username))",
     "legendFormat": "{{label_launcher_sas_com_username}}"
    }
   ]
  },
  {
   "title": "Memory Usage by User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($top,sum(:sas_launcher_pod_mem_usage_bytes:{pod=~\"$pod\"}) by (label_launcher_sas_com_username))",
     "legendFormat": "{{label_launcher_sas_com_username}}"
    }
   ]
  },
  {
   "title": "Filesystem I/O by User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($top,sum(rate(:sas_launcher_pod_fs_read_bytes_total:{pod=~\"$pod\"}[1m])) by (label_launcher_sas_com_username))",
     "legendFormat": "{{label_launcher_sas_com_username}} - Reads"
    },
    {
     "expr": "-topk($top,sum(rate(:sas_launcher_pod_fs_write_bytes_total:{pod=~\"$pod\"}[1m])) by (label_launcher_sas_com_username))",
     "legendFormat": "{{label_launcher_sas_com_username}} - Writes"
    }
   ]
  },
  {
   "title": "Network I/O by User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk($top,sum(rate(:sas_launcher_pod_net_receive_bytes_total:{pod=~\"$pod\"}[1m])) by (label_launcher_sas_com_username))",
     "legendFormat": "{{label_launcher_sas_com_username}} - Receive"
    },
    {
     "expr": "-topk($top,sum(rate(:sas_launcher_pod_net_transmit_bytes_total:{pod=~\"$pod\"}[1m])) by (label_launcher_sas_com_username))",
     "legendFormat": "{{label_launcher_sas_com_username}} - Transmit"
    }
   ]
  },
  {
   "title": "Active Job Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Jobs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": ":sas_launcher_pod_cpu_core_usage:{phase=~\"Pending|Running\",pod=~\"$pod\"}"
      },
      {
       "expr": ":sas_launcher_pod_mem_usage_bytes:{phase=~\"Pending|Running\",pod=~\"$pod\"}"
      },
      {
       "expr": "sum(:sas_launcher_pod_cpu_core_usage:{phase=~\"Pending|Running\",pod=~\"$pod\"}) by (pod,namespace) / sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod\"}) by (pod,namespace)"
      },
      {
       "expr": "sum(:sas_launcher_pod_mem_usage_bytes:{phase=~\"Pending|Running\",pod=~\"$pod\"}) by (pod,namespace) / sum(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\"}) by (pod,namespace)"
      }
     ]
    }
   ]
  }
 ]
}