{
 "title": "Kubernetes Deployment metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics ",
 "tags": [ "kubernetes-cluster" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Deployment", "query": "label_values(deployment)" },
   { "name": "Node", "query": "label_values(node)" }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{node=~\"^$Node$\",pod=~\"^$Deployment.*$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{node=~\"^$Node$\",pod=~\"^$Deployment.*$\"}[1m])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"^$Deployment$\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$Deployment$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{node=~\"^$Node$\",pod=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{node=~\"^$Node$\",pod=~\"^$Deployment.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"^$Deployment$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"^$Deployment$\"})"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod=~\"^$Deployment.*$\"}[1m])) by (io_kubernetes_container_name, pod)",
     "legendFormat": "pod: {{ pod }} | {{ io_kubernetes_container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",pod=~\"^$Deployment.*$\"}[1m])) by (pod, name, image)",
     "legendFormat": "docker: {{ pod }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",pod=~\"^$Deployment.*$\"}[1m])) by (pod, rkt_container_name)",
     "legendFormat": "rkt: {{ pod }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$Deployment.*$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod=~\"^$Deployment.*$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Deployment network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}