{
 "title": "Logging - Fluent Bit",
 "tags": [
  "logging",
  "fluentbit"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(fluentbit_output_proc_bytes_total, node)"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{daemonset=~\"fb-fluent-bit|v4m-fb\"}"
    }
   ]
  },
  {
   "title": "Message Rate (In/Out)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- sum(rate(fluentbit_input_records_total{node=~\"$node\"}[5m]))",
     "legendFormat": "In "
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{node=~\"$node\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{daemonset=~\"fb-fluent-bit|v4m-fb\"}"
    }
   ]
  },
  {
   "title": "Retries and Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fluentbit_output_retries_total{node=~\"$node\"}[2m]))",
     "legendFormat": "Retries"
    },
    {
     "expr": "sum (rate(fluentbit_output_retries_failed_total{node=~\"$node\"}[2m]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Throughput (Bytes In/Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- sum (rate(fluentbit_input_bytes_total{node=~\"$node\"}[2m]))",
     "legendFormat": "Input Bytes"
    },
    {
     "expr": "sum (rate(fluentbit_output_proc_bytes_total{node=~\"$node\"}[2m]))",
     "legendFormat": "Output Bytes"
    }
   ]
  },
  { "title": "By Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Message Rate (In/Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- sum(rate(fluentbit_input_records_total{node=~\"$node\"}[5m])) by (node)",
     "legendFormat": "In - {{ node }}"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{node=~\"$node\"}[5m])) by (node)",
     "legendFormat": "Out - {{ node }}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"fluent-bit\",node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Throughput (Bytes In/Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- sum (rate(fluentbit_input_bytes_total{node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Input Bytes - {{ node }}"
    },
    {
     "expr": "sum (rate(fluentbit_output_proc_bytes_total{node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Output Bytes - {{ node }}"
    }
   ]
  },
  {
   "title": "Retries and Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fluentbit_output_retries_total{node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Retries - {{ node }}"
    },
    {
     "expr": "sum (rate(fluentbit_output_retries_failed_total{node=~\"$node\"}[2m])) by (node)",
     "legendFormat": "Failures - {{ node }}"
    }
   ]
  }
 ]
}