{
 "title": "Perf / Container Utilization",
 "tags": [
  "kubernetes-cluster",
  "welcome-cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(kube_deployment_labels{namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "statefulset",
    "label": "statefulset",
    "query": "label_values(kube_statefulset_labels{namespace=~\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Use",
   "type": "table-old",
   "description": "NOTE: using rules metrics, and % values are \"current use\" as a % of cpu",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{pod}} - Req"
    },
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{pod}} - Lim"
    },
    {
     "expr": "(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range]))",
     "legendFormat": "{{pod}} - Max"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__range]))",
     "legendFormat": "{{pod}} - Avg"
    },
    {
     "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))",
     "legendFormat": "{{pod}} - Use(current)"
    },
    {
     "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{ pod }} - % of Req(current)"
    },
    {
     "expr": "sum by (pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})",
     "legendFormat": "{{ pod }} - % of Lim(current)"
    }
   ]
  },
  {
   "title": "Memory Use  (bytes)",
   "type": "table-old",
   "description": "NOTE: using rules metrics, and % values are \"current use\" as a % of mem",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{pod}} - Req"
    },
    {
     "expr": "sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{pod}} - Lim"
    },
    {
     "expr": "(max_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
     "legendFormat": "{{pod}} - MaxWss"
    },
    {
     "expr": "(avg_over_time(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__range]))",
     "legendFormat": "{{pod}} - AvgWss"
    },
    {
     "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r",
     "legendFormat": "{{pod}} - Use(current)"
    },
    {
     "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r / sum by (pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{ pod }} % of Req(current)"
    },
    {
     "expr": "sum by (pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"})\r / sum by (pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{ pod }} % of Lim(current)"
    }
   ]
  },
  {
   "title": "Total CPU use & req",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "sum  (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\"})\r",
     "legendFormat": "Requested: {{ container }}"
    }
   ]
  },
  {
   "title": "Total MEM use & req",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum  (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", container!=\"POD\"})\r",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "sum  (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\"})\r",
     "legendFormat": "Requested: {{ container }}"
    }
   ]
  },
  {
   "title": "CPU use",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "{{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "MEM use",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "{{ container }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "% CPU use / req",
   "type": "graph",
   "description": "100% (consider increasing req)\n0% (sized just right)\n-100% (consider decreasing req)",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})\r ))\n",
     "legendFormat": "cpuUse/req {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% MEM use / req",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) / sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) ))\r\n",
     "legendFormat": "memUse/req: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% CPU use / lim",
   "type": "graph",
   "description": "100% (consider increasing req)\n0% (sized just right)\n-100% (consider decreasing req)",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m])) / sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) ))\r",
     "legendFormat": "cpuUse/req {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% MEM use / lim",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) / sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\" }) ))\r\n",
     "legendFormat": "memUse/req: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "CPU use, req, lim",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[4m]))\r",
     "legendFormat": "Current: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})\r",
     "legendFormat": "Requested: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})\r",
     "legendFormat": "Limit: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "MEM use, req, lim, cache",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "Current: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"                  })\r",
     "legendFormat": "Requested: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"                  })\r",
     "legendFormat": "Limit: {{ container }}/{{pod}}"
    },
    {
     "expr": "sum by(pod,container) (container_memory_cache{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"})\r",
     "legendFormat": "Cache: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\"}[4m])))",
     "legendFormat": "RX: {{ pod }}"
    },
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\", namespace=~\"$namespace\", pod=~\"$pod\"}[4m])))",
     "legendFormat": "TX: {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Restarts Per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod,container) (kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Restarts: {{pod}}/{{ container }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors per Pod -- \"endpoint/sas_service_base/service (node)\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"$namespace\", pod=~\"$pod\"}\r ",
     "legendFormat": "{{endpoint}}/{{sas_service_base}}/{{service}} ({{node}})"
    }
   ]
  },
  {
   "title": "Replicas (by Deployment)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$pod\"})\r\n",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Replicas (by HPA)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(hpa) (kube_hpa_status_current_replicas{namespace=~\"$namespace\"})\r\n",
     "legendFormat": "{{hpa}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"$namespace\", pod=~\"$pod\"}\r ",
     "legendFormat": "{{endpoint}}/{{sas_service_base}}/{{service}} ({{node}})"
    }
   ]
  }
 ]
}