{
 "title": "Perf / Kubernetes Headroom",
 "tags": [
  "kubernetes-cluster",
  "welcome-cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Allocatable CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes)\r)"
    }
   ]
  },
  {
   "title": "Total Allocatable Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{})"
    }
   ]
  },
  {
   "title": "Total Allocatable CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores) - sum(kube_pod_container_resource_requests_cpu_cores)\r"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes) - sum(kube_pod_container_resource_requests_memory_bytes)\r)"
    }
   ]
  },
  {
   "title": "Total Allocatable Pods Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{}) - sum(kubelet_running_pod_count{job=\"kubelet\", metrics_path=\"/metrics\"})\r"
    }
   ]
  },
  {
   "title": "% Allocatable CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (sum(kube_node_status_allocatable_cpu_cores) - sum(kube_pod_container_resource_requests_cpu_cores)) / sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "% Allocatable Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(sum(kube_node_status_allocatable_memory_bytes) - sum(kube_pod_container_resource_requests_memory_bytes)\r)/sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "% Allocatable Pods Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (sum(kube_node_status_allocatable_pods{}) - sum(kubelet_running_pod_count{job=\"kubelet\", metrics_path=\"/metrics\"})) / sum(kube_node_status_allocatable_pods{})\r"
    }
   ]
  },
  {
   "title": "Resources by Namespace",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)",
     "legendFormat": "cpu req"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)",
     "legendFormat": "mem req"
    },
    {
     "expr": "count(mixin_pod_workload) by (namespace)",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Resources by Node",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{job=\"kubelet\", metrics_path=\"/metrics\"}) by (node)",
     "legendFormat": "Pod Count"
    },
    {
     "expr": "sum(kube_node_status_allocatable_pods{}) by (node)",
     "legendFormat": "Pods Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{})\r by (node)",
     "legendFormat": "CPU Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{}) by (node)",
     "legendFormat": "CPU Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{}) by (node)",
     "legendFormat": "Mem Requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{}) by (node)",
     "legendFormat": "Mem Allocatable"
    }
   ]
  }
 ]
}